DROP TABLE IF EXISTS PERSISTENT_LOGINS;

CREATE TABLE PERSISTENT_LOGINS (
   username VARCHAR(64) NOT NULL,
   series VARCHAR(64) PRIMARY KEY,
   token VARCHAR(64) NOT NULL,
   last_used TIMESTAMP NOT NULL
);